# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cgpa_calc_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:9a67475d40c6a5a94047a006c71047648356f14064a7f9850c9304a0808006e0}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION:86400000}

# Google Auth
google.client.id=${GOOGLE_CLIENT_ID:414100923470-q5al9v0ogrp49sl9sjbvrfipj1e0tr2h.apps.googleusercontent.com}

# CORS Configuration
app.cors.allowed-origins=${ALLOWED_ORIGINS:https://cgpa-calculator-ac-in.onrender.com}
